apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_HOST: ${AWS_RDS_ENDPOINT}
  POSTGRES_DB: auth_db
  POSTGRES_USER: <db-user>
  POSTGRES_PASSWORD: <db-pass>
  
  # Os valores DEVEM estar em base64112
  ## POSTGRES_USER: dG1fdXNlcg==
  ## POSTGRES_PASSWORD: dG1fcGFzc18yNg==
  ## POSTGRES_DB: YXV0aF9kYg==
