apiVersion: v1
kind: Secret
metadata:
  name: flag-db-secret
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_HOST: ${AWS_RDS_ENDPOINT}
  POSTGRES_DB: flag_db
  POSTGRES_USER: <db-user>
  POSTGRES_PASSWORD: <db-pass>

  # Os valores DEVEM estar em base64
  #POSTGRES_USER: dG1fdXNlcg==
  #POSTGRES_PASSWORD: dG1fcGFzcw==
  #POSTGRES_DB: ZmxhZ3NfZGI=